[package]
name = "libm-test"
version = "0.1.0"
authors = ["Gonzalo Brito Gadeschi <gonzalobg88@gmail.com>"]
edition = "2018"

[dev-dependencies]
libm = { path = "../libm" }
libm-analyze = { path = "../libm-analyze", no-default-features = true }
rand = "0.7"

[features]
default = []
checked = ["libm/checked"]
